server:
  port: 7001
eureka:
  instance:
    hostname: eurekaserver7001.com
    instance-id: eurekaserver7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver7002.com:7002/eureka/
spring:
  application:
    name: eurekaserver
